### ISSUE TITLE
Add U control chart calculator

### ISSUE THREAD

**Issue by Khushi-agarwal** [makesmatheasy/makesmatheasy#5329]
## **Is your feature request related to a problem? Please describe.**

I would like to add U control chart under the statistics section

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by Khushi-agarwal** [comment]
@arpit456jain kindly assign me this issue.

**Comment by arpit456jain** [comment]
Go ahead @Khushi-agarwal 
Deadline 2 july

**Comment by sairish2001** [comment]
Actually we focus more on Calculators, so try adding calculators, or You can modify functions to library functions, means functions till now getting values by DOM element, directly inside the functions, we want just pass the values as parameters, and it will return a Result and Steps. 
I think you are familiar with it, because you already made, various Calculators @Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
> Actually we focus more on Calculators, so try adding calculators, or You can modify functions to library functions, means functions till now getting values by DOM element, directly inside the functions, we want just pass the values as parameters, and it will return a Result and Steps.
> I think you are familiar with it, because you already made, various Calculators @Khushi-agarwal

Actually @sairish2001 this issue was regarding the creation of calculator only...like there are p chart calculator, similarly I want to add u control chart calculator.

**Comment by sairish2001** [comment]
Okay fine!
Next time do mention, that you are planning to add a Calculator.

**Comment by Khushi-agarwal** [comment]
> Okay fine!
> Next time do mention, that you are planning to add a Calculator.

I have updated it now and sorry for the confusion. i should have mentioned it earlier.
